# Site settings
title: Coding Blog
email: michael.wiss@gmail.com
description: A blog about learning to code.
baseurl: '/coding_blog'
url: "http://coding.me" # the base hostname & protocol for your site
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" #an empty string here means all files in the project
      type: "posts" # previously 'post' in jekyll 2.2
    values:
      author: Michael Wiss
      layout: "post"
      category: coding
  -
    scope:
      path: "" #an empty string here means all files in the project
      type: "pages" # previously 'post' in jekyll 2.2
    values:
      layout: "page"